=== AliRadwan1/FourthYear_FirstSemester/Service-Oriented Architecture - IS434/Labs/Lab 2/Demos/xsd_example/students.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="students">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="student" minOccurs="0" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                        <xs:element name="name" type="xs:string" />
                        <xs:element name="year" type="xs:string" />
                        <xs:element name="testgrade" type="xs:int" minOccurs="0"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== AliRadwan1/FourthYear_FirstSemester/Service-Oriented Architecture - IS434/Labs/Lab 2/Demos/xsd_example/students.xml
<?xml version="1.0" encoding="UTF-8"?>
<students xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="students.xsd">
    <student>
        <name>Joe Jones</name>
        <year>Sophomore</year>
        <testgrade>95</testgrade>
    </student>
    <student>
        <name>Mary Smith</name>
        <year>Senior</year>
        <testgrade>87</testgrade>
    </student>
    <student>
        <name>Linda Brown</name>
        <year>Junior</year>
        <testgrade>92</testgrade>
    </student>
</students>
